name: Tính năng mới
description: Đề xuất cải tiến cho react-native-iconify
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã chia sẻ ý tưởng! Điền thông tin bên dưới để chúng tôi hiểu rõ nhu cầu.
  - type: textarea
    id: problem
    attributes:
      label: Vấn đề hiện tại
      placeholder: Người dùng web cần lazy-load icon nhưng hiện chưa có hướng dẫn...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Giải pháp mong muốn
      placeholder: Thêm option trong loader để sinh dynamic import, ví dụ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Giải pháp khác đã thử
  - type: textarea
    id: extra
    attributes:
      label: Thông tin bổ sung

