#!/usr/bin/env node
/**
 * Icon Scanner
 *
 * Scans codebase for IconifyIcon component usage and extracts icon names from the `name` prop.
 *
 * Apps commonly wrap IconifyIcon in their own component (`<AppIcon name="mdi:heart" />`).
 * The scanner therefore runs in two phases:
 *   1. Find local components that render IconifyIcon and forward the `name` prop.
 *   2. Treat usages of those wrappers as icon usages too.
 *
 * On top of that, a Tailwind-style literal scan reads every string literal in the scanned
 * files and keeps the ones that look like an icon name. A candidate must pass three
 * filters before it is bundled:
 *   1. shape  - full-string match of `prefix:icon-name`
 *   2. prefix - the prefix is a known Iconify collection (scripts/iconify-prefixes.json)
 *   3. existence - the Iconify API drops names it does not know at fetch time
 * A false positive costs a few hundred bytes in the bundle; a false negative costs one
 * runtime fetch - so the scan can afford to be greedy. Set `iconify.detection` to
 * "strict" in package.json to turn the literal tiers off.
 *
 * Names that cannot be resolved statically (`name={variable}`) are reported so they can be
 * declared explicitly via the `iconify` field in package.json.
 */

const fs = require("fs");
const path = require("path");

const CONFIG = {
  scanDirs: [
    "src",
    "app",
    "screens",
    "components",
    "pages",
    "views",
    "modules",
    "features",
    "navigation",
    "layouts",
    "containers",
    "ui",
    "common",
    "shared",
    "lib",
    "constants",
    "config",
    "tabs",
    "modals",
    "overlays",
    "widgets",
    "atoms",
    "molecules",
    "organisms",
    "templates",
    "elements",
    "core",
    "design-system",
    "packages",
  ],
  extensions: [".tsx", ".ts", ".jsx", ".js"],
  ignore: [
    "node_modules",
    ".expo",
    ".git",
    "dist",
    "build",
    "__tests__",
    "__mocks__",
    ".test.",
    ".spec.",
    "coverage",
    ".storybook",
    "storybook",
    "android",
    "ios",
    ".next",
    "out",
    "bundled-icons.generated",
  ],
  componentNames: ["IconifyIcon"],
  importSources: [
    "@huymobile/react-native-iconify",
    "react-native-iconify",
    "../components/IconifyIcon",
    "./IconifyIcon",
  ],
  // How many levels of wrapper indirection to follow (a wrapper of a wrapper of ...).
  maxWrapperDepth: 3,
  // Maximum number of unresolved usages printed in the summary.
  maxUnresolvedReported: 10,
};

// Known Iconify collection prefixes (mdi, lucide, tabler, ...), generated by
// scripts/update-prefixes.js. Missing file disables the prefix-validated tiers
// only - the import/wrapper scan is unaffected.
let KNOWN_PREFIXES = new Set();
try {
  KNOWN_PREFIXES = new Set(require("./iconify-prefixes.json"));
} catch (err) {
  // Fall through with an empty set.
}

const ICON_SHAPE = /^[a-z0-9]+(?:-[a-z0-9]+)*:[a-z0-9]+(?:-[a-z0-9]+)*$/;
// `mdi:` or `mdi:weather-` before a `${...}` hole in a template literal.
const TEMPLATE_ICON_HEAD = /^([a-z0-9]+(?:-[a-z0-9]+)*):([a-z0-9-]*)$/;

function shouldIgnore(filePath) {
  return CONFIG.ignore.some((pattern) => filePath.includes(pattern));
}

/**
 * Every string literal in `content`, with comments skipped so example names in
 * JSDoc are not bundled. Template literals with `${...}` holes are returned
 * separately: their fixed pieces are never icon candidates, but a head like
 * `mdi:weather-` is evidence of dynamic construction worth warning about.
 *
 * This is a plain-text pass, not a parser: a regex literal containing a quote
 * can throw it off for a stretch, in which case it captures junk - and junk
 * never survives `isIconCandidate`. Same trade-off Tailwind makes.
 */
function extractStringLiterals(content) {
  const literals = [];
  const templates = [];
  let i = 0;

  while (i < content.length) {
    const char = content[i];
    const next = content[i + 1];

    if (char === "/" && next === "/") {
      const newline = content.indexOf("\n", i);
      i = newline === -1 ? content.length : newline + 1;
      continue;
    }

    if (char === "/" && next === "*") {
      const close = content.indexOf("*/", i + 2);
      i = close === -1 ? content.length : close + 2;
      continue;
    }

    if (char === '"' || char === "'") {
      const start = i + 1;
      i = start;
      while (i < content.length && content[i] !== char && content[i] !== "\n") {
        i += content[i] === "\\" ? 2 : 1;
      }
      literals.push({ value: content.slice(start, i), index: start });
      i++;
      continue;
    }

    if (char === "`") {
      const start = i;
      let piece = "";
      let head = null;
      let interpolated = false;
      i++;

      while (i < content.length && content[i] !== "`") {
        if (content[i] === "\\") {
          i += 2;
          continue;
        }

        if (content[i] === "$" && content[i + 1] === "{") {
          if (!interpolated) {
            head = piece;
          }
          interpolated = true;
          piece = "";
          i += 2;

          let depth = 1;
          let quote = null;

          while (i < content.length && depth > 0) {
            const inner = content[i];

            if (quote) {
              if (inner === "\\") {
                i++;
              } else if (inner === quote) {
                quote = null;
              }
            } else if (inner === '"' || inner === "'" || inner === "`") {
              quote = inner;
            } else if (inner === "{") {
              depth++;
            } else if (inner === "}") {
              depth--;
            }

            i++;
          }
          continue;
        }

        piece += content[i];
        i++;
      }

      if (interpolated) {
        templates.push({ head: head || "", index: start });
      } else {
        literals.push({ value: piece, index: start + 1 });
      }

      i++;
      continue;
    }

    i++;
  }

  return { literals, templates };
}

function isIconCandidate(value, extraPrefixes) {
  if (!ICON_SHAPE.test(value)) {
    return false;
  }

  const prefix = value.split(":")[0];

  return KNOWN_PREFIXES.has(prefix) || extraPrefixes.has(prefix);
}

/**
 * `mdi:weather-*` -> /^mdi:weather-[a-z0-9-]*$/ - used for the safelist globs
 * expanded at bundle time and for `iconify.exclude` patterns.
 */
function globToRegex(pattern) {
  const escaped = pattern
    .split("*")
    .map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("[a-z0-9-]*");

  return new RegExp(`^${escaped}$`);
}

function matchesIconGlob(pattern, iconName) {
  return pattern.includes("*")
    ? globToRegex(pattern).test(iconName)
    : pattern === iconName;
}

/**
 * Tailwind-style tier: icon-shaped string literals anywhere in the file,
 * validated against the known-prefix list. Also reports template literals that
 * *construct* an icon name (`mdi:${x}`), which no literal scan can resolve.
 */
function literalScanFile(content, extraPrefixes) {
  const { literals, templates } = extractStringLiterals(content);
  const icons = new Set();
  const constructions = [];

  literals.forEach(({ value }) => {
    const candidate = value.trim().toLowerCase();

    if (isIconCandidate(candidate, extraPrefixes)) {
      icons.add(candidate);
    }
  });

  templates.forEach(({ head, index }) => {
    const match = TEMPLATE_ICON_HEAD.exec(head.trim().toLowerCase());

    if (match && (KNOWN_PREFIXES.has(match[1]) || extraPrefixes.has(match[1]))) {
      constructions.push({
        head: head.trim(),
        suggestion: `${head.trim()}*`,
        line: content.slice(0, index).split("\n").length,
      });
    }
  });

  return { icons, constructions };
}

function getAllFiles(dir, fileList = []) {
  if (!fs.existsSync(dir) || shouldIgnore(dir)) {
    return fileList;
  }

  const files = fs.readdirSync(dir);

  files.forEach((file) => {
    const filePath = path.join(dir, file);

    if (shouldIgnore(filePath)) {
      return;
    }

    const stat = fs.statSync(filePath);

    if (stat.isDirectory()) {
      getAllFiles(filePath, fileList);
    } else if (CONFIG.extensions.some((ext) => file.endsWith(ext))) {
      fileList.push(filePath);
    }
  });

  return fileList;
}

function hasIconifyImport(content) {
  const importPatterns = [
    /import\s+.*IconifyIcon.*from\s+["']@huymobile\/react-native-iconify["']/,
    /import\s+.*IconifyIcon.*from\s+["']react-native-iconify["']/,
    /import\s+\{\s*IconifyIcon\s*\}\s*from/,
    /require\s*\(\s*["']@huymobile\/react-native-iconify["']\s*\)/,
    /require\s*\(\s*["']react-native-iconify["']\s*\)/,
  ];

  return importPatterns.some((pattern) => pattern.test(content));
}

/**
 * Find every opening JSX tag for `componentName` and return its attribute text.
 * Tracks quotes and brace depth so props containing `>` (arrow functions),
 * object/array literals and `{...spread}` do not truncate the tag.
 */
function findComponentTags(content, componentName) {
  const tags = [];
  const opening = `<${componentName}`;
  let cursor = 0;

  while (cursor < content.length) {
    const start = content.indexOf(opening, cursor);

    if (start === -1) {
      break;
    }

    const attrsStart = start + opening.length;
    cursor = attrsStart;

    // Avoid matching a longer component name (<IconifyIconGroup, <Icon.Base)
    if (/[A-Za-z0-9_$.-]/.test(content[attrsStart] || "")) {
      continue;
    }

    let depth = 0;
    let quote = null;
    let end = -1;

    for (let i = attrsStart; i < content.length; i++) {
      const char = content[i];

      if (quote) {
        if (char === "\\") {
          i++;
        } else if (char === quote) {
          quote = null;
        }
        continue;
      }

      if (char === '"' || char === "'" || char === "`") {
        quote = char;
      } else if (char === "{") {
        depth++;
      } else if (char === "}") {
        depth = Math.max(0, depth - 1);
      } else if (char === ">" && depth === 0) {
        end = i;
        break;
      }
    }

    if (end === -1) {
      break;
    }

    tags.push({
      index: start,
      attrs: content.slice(attrsStart, end).replace(/\/\s*$/, ""),
    });

    cursor = end + 1;
  }

  return tags;
}

/**
 * Read a JSX attribute value, ignoring identical identifiers nested inside other
 * props (e.g. `style={[{ name: "x" }]}`).
 * Returns the raw value expression, or null when the attribute is absent.
 */
function readAttribute(attrs, attrName) {
  const pattern = new RegExp(`(^|[^A-Za-z0-9_$.])${attrName}\\s*=`, "g");
  let depth = 0;
  let quote = null;
  const topLevel = new Array(attrs.length).fill(false);

  for (let i = 0; i < attrs.length; i++) {
    const char = attrs[i];

    if (quote) {
      if (char === "\\") {
        i++;
      } else if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'" || char === "`") {
      quote = char;
    } else if (char === "{") {
      depth++;
    } else if (char === "}") {
      depth = Math.max(0, depth - 1);
    } else {
      topLevel[i] = depth === 0;
    }
  }

  let match;
  while ((match = pattern.exec(attrs)) !== null) {
    const nameIndex = match.index + match[1].length;

    if (topLevel[nameIndex]) {
      return attrs.slice(match.index + match[0].length).trim();
    }
  }

  return null;
}

/**
 * Resolve a JSX attribute value to a literal string, or null when it is dynamic.
 */
function staticStringValue(rawValue) {
  if (!rawValue) {
    return null;
  }

  const patterns = [
    /^["']([^"']*)["']/,
    /^\{\s*["']([^"']*)["']\s*\}/,
    /^\{\s*`([^`]*)`\s*\}/,
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(rawValue);

    if (match && !match[1].includes("${")) {
      return match[1].trim();
    }
  }

  return null;
}

function isSpreadOnly(attrs) {
  return /\{\s*\.\.\.[A-Za-z_$]/.test(attrs);
}

/**
 * True when the `name` prop is passed straight through (`name={name}` or `{...props}`).
 * Deliberately narrow: `name={cond ? "a:b" : "c:d"}` is not forwarding, it is an
 * unresolvable usage and must be reported as one.
 */
function forwardsName(attrs, rawValue) {
  if (rawValue === null) {
    return isSpreadOnly(attrs);
  }

  return /^\{\s*[A-Za-z_$][A-Za-z0-9_$]*\s*\}/.test(rawValue);
}

/**
 * The attribute value on its own, for reporting: `{cond ? "a:b" : "c:d"}`.
 */
function valueExpression(rawValue) {
  if (rawValue[0] !== "{") {
    return (/^["'][^"']*["']/.exec(rawValue) || [rawValue])[0];
  }

  let depth = 0;

  for (let i = 0; i < rawValue.length; i++) {
    if (rawValue[i] === "{") {
      depth++;
    } else if (rawValue[i] === "}") {
      depth--;

      if (depth === 0) {
        return rawValue.slice(0, i + 1).replace(/\s+/g, " ");
      }
    }
  }

  return rawValue.split("\n")[0];
}

/**
 * Name of the (capitalised) component declaration that encloses `index`.
 */
function enclosingComponentName(content, index) {
  const declaration =
    /(?:^|[\n;])\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+([A-Z][A-Za-z0-9_$]*)|(?:^|[\n;])\s*(?:export\s+)?(?:const|let|var)\s+([A-Z][A-Za-z0-9_$]*)\s*(?::[^=\n]*)?=/g;
  const before = content.slice(0, index);
  let owner = null;
  let match;

  while ((match = declaration.exec(before)) !== null) {
    owner = match[1] || match[2];
  }

  return owner;
}

/**
 * Local bindings introduced by every `import ... from "source"` statement.
 */
function parseImports(content) {
  // Anchored to the start of a line so the word "import" inside a comment or a
  // string does not swallow the following statement.
  const importPattern = /(?:^|[\n;])\s*import\s+([^;'"]*?)\s+from\s+["']([^"']+)["']/g;
  const imports = [];
  let match;

  while ((match = importPattern.exec(content)) !== null) {
    const clause = match[1];
    const locals = [];
    const named = /\{([^}]*)\}/.exec(clause);

    if (named) {
      named[1].split(",").forEach((entry) => {
        const binding = entry.trim().replace(/^type\s+/, "");

        if (!binding) {
          return;
        }

        const aliased = /\s+as\s+([A-Za-z_$][A-Za-z0-9_$]*)$/.exec(binding);
        locals.push(aliased ? aliased[1] : binding.split(/\s+/)[0]);
      });
    }

    const namespaced = /\*\s+as\s+([A-Za-z_$][A-Za-z0-9_$]*)/.exec(clause);

    if (namespaced) {
      locals.push(namespaced[1]);
    }

    const defaultBinding = clause
      .replace(/\{[^}]*\}/, "")
      .replace(/^type\s+/, "")
      .split(",")[0]
      .trim();

    if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(defaultBinding)) {
      locals.push(defaultBinding);
    }

    imports.push({ source: match[2], locals });
  }

  return imports;
}

/**
 * Key used to match an import specifier against the file that declares a wrapper.
 * Path aliases (`@/components/AppIcon`) and relative paths both reduce to "AppIcon",
 * so a default import can be renamed at the call site and still be resolved.
 */
function moduleKey(specifier) {
  const segments = specifier
    .replace(/\.(tsx|ts|jsx|js)$/, "")
    .split(/[\\/]/)
    .filter((segment) => segment && segment !== "." && segment !== "..");

  if (segments.length === 0) {
    return null;
  }

  const last = segments[segments.length - 1];

  if (last === "index" && segments.length > 1) {
    return segments[segments.length - 2];
  }

  return last;
}

/**
 * Icon component names usable in a single file: IconifyIcon itself (when imported),
 * any wrapper declared in the file, and any wrapper imported into it.
 *
 * Maps the local binding to the name the wrapper was declared under, so a renamed
 * default import (`import Glyph from "./AppIcon"`) is still credited to AppIcon.
 */
function iconComponentsForFile(file, content, wrappers, extraComponents) {
  const components = new Map();

  extraComponents.forEach((name) => components.set(name, name));

  if (hasIconifyImport(content)) {
    CONFIG.componentNames.forEach((name) => components.set(name, name));
  }

  (wrappers.byFile.get(file) || []).forEach((name) => components.set(name, name));

  parseImports(content).forEach(({ source, locals }) => {
    const declared = wrappers.namesByModule.get(moduleKey(source));

    locals.forEach((local) => {
      if (declared) {
        components.set(local, declared.has(local) ? local : declared.values().next().value);
      } else if (wrappers.names.has(local)) {
        components.set(local, local);
      }
    });
  });

  return components;
}

/**
 * Components in `content` that render an icon component and forward `name` to it.
 * Returns the wrapper names plus a map of tag index -> wrapper name, so the second
 * phase can tell a resolved forward apart from an unresolvable usage.
 */
function findWrapperComponents(content, iconComponents) {
  const names = new Set();
  const forwardingTags = new Map();

  iconComponents.forEach((canonical, component) => {
    findComponentTags(content, component).forEach((tag) => {
      if (!forwardsName(tag.attrs, readAttribute(tag.attrs, "name"))) {
        return;
      }

      const owner = enclosingComponentName(content, tag.index);

      if (owner) {
        names.add(owner);
        forwardingTags.set(tag.index, owner);
      }
    });
  });

  return { names, forwardingTags };
}

/**
 * Icon names spelled out in props objects and icon arrays rather than in JSX.
 * Unchanged heuristics, kept scoped to files that import IconifyIcon directly.
 */
function extractIconNamesFromPatterns(content) {
  const iconNames = new Set();

  const spreadPatterns = [
    /IconifyIcon[^}]*name\s*:\s*["']([^"']+)["']/g,
    /\{\s*name\s*:\s*["']([a-z0-9-]+:[a-z0-9-]+)["'][^}]*\}[^<]*<IconifyIcon/gi,
  ];

  spreadPatterns.forEach((pattern) => {
    let match;
    while ((match = pattern.exec(content)) !== null) {
      const iconName = match[1].trim();
      if (iconName && iconName.includes(":") && !iconName.includes("${")) {
        iconNames.add(iconName.toLowerCase());
      }
    }
  });

  const arrayPatterns = [
    /const\s+\w*[Ii]cons?\w*\s*=\s*\[([^\]]+)\]/g,
    /\w*[Ii]cons?\w*\s*:\s*\[([^\]]+)\]/g,
  ];

  arrayPatterns.forEach((pattern) => {
    let match;
    while ((match = pattern.exec(content)) !== null) {
      const arrayContent = match[1];
      const stringPattern = /["']([a-z0-9-]+:[a-z0-9-]+)["']/gi;
      let stringMatch;
      while ((stringMatch = stringPattern.exec(arrayContent)) !== null) {
        const iconName = stringMatch[1].trim();
        if (iconName && iconName.includes(":")) {
          iconNames.add(iconName.toLowerCase());
        }
      }
    }
  });

  return iconNames;
}

/**
 * String literals inside a dynamic `name={...}` expression that pass the shape
 * and prefix filters. `name={active ? "mdi:check" : "mdi:close"}` yields both
 * icons; `name={t("common:back")}` yields nothing, because `common` is not an
 * Iconify collection - which is exactly why scraping is safe to do at all.
 */
function scrapeExpressionLiterals(expression, extraPrefixes) {
  const { literals } = extractStringLiterals(expression);
  const icons = new Set();

  literals.forEach(({ value }) => {
    const candidate = value.trim().toLowerCase();

    if (isIconCandidate(candidate, extraPrefixes)) {
      icons.add(candidate);
    }
  });

  return Array.from(icons);
}

/**
 * Icon names used through `componentNames` in a single file.
 *
 * `unresolved` holds usages whose `name` prop is not a static string.
 * `forwarded` holds `name={name}` pass-throughs inside a wrapper: they are only
 * genuinely resolved if the wrapper itself was matched with static names elsewhere,
 * which is decided once the whole project has been scanned.
 * `scraped` holds dynamic expressions whose string literals were bundled.
 */
function extractFromComponents(content, componentNames, forwardingTags, options = {}) {
  const iconNames = new Set();
  const unresolved = [];
  const forwarded = [];
  const scraped = [];
  const resolvedBy = new Map();
  const components =
    componentNames instanceof Map
      ? componentNames
      : new Map(Array.from(componentNames, (name) => [name, name]));

  components.forEach((canonical, component) => {
    findComponentTags(content, component).forEach((tag) => {
      const rawValue = readAttribute(tag.attrs, "name");

      if (rawValue === null) {
        return;
      }

      const iconName = staticStringValue(rawValue);

      if (iconName) {
        if (iconName.includes(":")) {
          iconNames.add(iconName.toLowerCase());
          resolvedBy.set(canonical, (resolvedBy.get(canonical) || 0) + 1);
        }
        return;
      }

      const expression = valueExpression(rawValue);
      const usage = {
        component,
        wrapper: forwardingTags.get(tag.index) || null,
        line: content.slice(0, tag.index).split("\n").length,
        expression: expression.slice(0, 60),
      };

      if (usage.wrapper) {
        forwarded.push(usage);
        return;
      }

      if (options.scrapeExpressions) {
        const icons = scrapeExpressionLiterals(expression, options.extraPrefixes);

        if (icons.length > 0) {
          icons.forEach((icon) => iconNames.add(icon));
          resolvedBy.set(canonical, (resolvedBy.get(canonical) || 0) + 1);
          scraped.push({ ...usage, icons });
          return;
        }
      }

      unresolved.push(usage);
    });
  });

  return { iconNames, unresolved, forwarded, scraped, resolvedBy };
}

function extractIconNamesFromComponent(content, componentNames = CONFIG.componentNames) {
  const { iconNames } = extractFromComponents(content, componentNames, new Map());

  extractIconNamesFromPatterns(content).forEach((icon) => iconNames.add(icon));

  return Array.from(iconNames);
}

function extractIconNames(content) {
  if (!hasIconifyImport(content)) {
    return [];
  }
  return extractIconNamesFromComponent(content);
}

/**
 * Optional escape hatch for what static analysis cannot reach:
 *   {
 *     "iconify": {
 *       "components": ["MyIcon"],
 *       "icons": ["mdi:heart", "mdi:weather-*"],
 *       "detection": "smart",
 *       "extraPrefixes": ["my-custom-set"],
 *       "exclude": ["carbon:user"]
 *     }
 *   }
 *
 * `icons` entries containing `*` are safelist globs, expanded against the
 * collection's icon list at bundle time. `detection: "strict"` turns off the
 * literal-scan tiers. `extraPrefixes` extends the known-prefix allowlist for
 * self-hosted icon sets. `exclude` removes names (or glob patterns) from the
 * final bundle.
 */
function loadUserConfig(projectRoot) {
  const config = {
    components: [],
    icons: [],
    iconGlobs: [],
    detection: "smart",
    extraPrefixes: new Set(),
    exclude: [],
  };

  try {
    const packageJson = JSON.parse(
      fs.readFileSync(path.join(projectRoot, "package.json"), "utf-8")
    );
    const userConfig = packageJson.iconify;

    if (userConfig && typeof userConfig === "object") {
      if (Array.isArray(userConfig.components)) {
        config.components = userConfig.components.filter(
          (name) => typeof name === "string" && name.length > 0
        );
      }

      if (Array.isArray(userConfig.icons)) {
        userConfig.icons.forEach((name) => {
          if (typeof name !== "string" || !name.includes(":")) {
            return;
          }

          if (name.includes("*")) {
            config.iconGlobs.push(name);
          } else {
            config.icons.push(name);
          }
        });
      }

      if (userConfig.detection === "strict") {
        config.detection = "strict";
      }

      if (Array.isArray(userConfig.extraPrefixes)) {
        userConfig.extraPrefixes.forEach((prefix) => {
          if (typeof prefix === "string" && prefix.length > 0) {
            config.extraPrefixes.add(prefix.toLowerCase());
          }
        });
      }

      if (Array.isArray(userConfig.exclude)) {
        config.exclude = userConfig.exclude.filter(
          (name) => typeof name === "string" && name.includes(":")
        );
      }
    }
  } catch (err) {
    // No package.json or invalid JSON - fall back to static analysis only
  }

  return config;
}

function collectProjectFiles(projectRoot) {
  const files = [];

  try {
    fs.readdirSync(projectRoot).forEach((file) => {
      const filePath = path.join(projectRoot, file);

      if (
        fs.statSync(filePath).isFile() &&
        CONFIG.extensions.some((ext) => file.endsWith(ext)) &&
        !shouldIgnore(filePath)
      ) {
        files.push(filePath);
      }
    });
  } catch (err) {
    // Ignore errors reading root directory
  }

  CONFIG.scanDirs.forEach((dir) => {
    const dirPath = path.resolve(projectRoot, dir);

    if (fs.existsSync(dirPath)) {
      getAllFiles(dirPath).forEach((file) => files.push(file));
    }
  });

  return files;
}

/**
 * Discover wrapper components, following up to CONFIG.maxWrapperDepth levels of
 * indirection (a wrapper of a wrapper of IconifyIcon).
 */
function discoverWrappers(sources, extraComponents) {
  const wrappers = {
    names: new Set(),
    namesByModule: new Map(),
    byFile: new Map(),
    forwardingTags: new Map(),
  };

  for (let depth = 0; depth < CONFIG.maxWrapperDepth; depth++) {
    let discovered = 0;

    sources.forEach(({ file, content }) => {
      const components = iconComponentsForFile(file, content, wrappers, extraComponents);

      if (components.size === 0) {
        return;
      }

      const { names, forwardingTags } = findWrapperComponents(content, components);
      const fileNames = new Set(wrappers.byFile.get(file) || []);

      names.forEach((name) => {
        if (!wrappers.names.has(name)) {
          discovered++;
        }

        wrappers.names.add(name);
        fileNames.add(name);
      });

      if (fileNames.size > 0) {
        wrappers.byFile.set(file, fileNames);
        wrappers.forwardingTags.set(file, forwardingTags);

        const key = moduleKey(file);

        if (key) {
          wrappers.namesByModule.set(key, fileNames);
        }
      }
    });

    if (discovered === 0) {
      break;
    }
  }

  return wrappers;
}

function scanProject(projectRoot = process.cwd()) {
  const allIcons = new Set();
  const allUnresolved = [];
  const allForwarded = [];
  const allScraped = [];
  const resolvedByComponent = new Map();
  let filesWithIcons = 0;
  let filesWithImport = 0;

  console.log("🔍 [Iconify] Scanning for IconifyIcon component usage...\n");

  const userConfig = loadUserConfig(projectRoot);
  const smart = userConfig.detection === "smart";
  const sources = collectProjectFiles(projectRoot).map((file) => ({
    file,
    content: fs.readFileSync(file, "utf-8"),
  }));

  const wrappers = discoverWrappers(sources, userConfig.components);

  userConfig.icons.forEach((icon) => allIcons.add(icon.toLowerCase()));

  sources.forEach(({ file, content }) => {
    const hasImport = hasIconifyImport(content);

    if (hasImport) {
      filesWithImport++;
    }

    const components = iconComponentsForFile(file, content, wrappers, userConfig.components);

    if (components.size === 0) {
      return;
    }

    const { iconNames, unresolved, forwarded, scraped, resolvedBy } = extractFromComponents(
      content,
      components,
      wrappers.forwardingTags.get(file) || new Map(),
      { scrapeExpressions: smart, extraPrefixes: userConfig.extraPrefixes }
    );

    // Legacy heuristics (icon arrays, `name:` in props objects) stay scoped to files
    // that import IconifyIcon directly, exactly as before.
    if (hasImport) {
      extractIconNamesFromPatterns(content).forEach((icon) => iconNames.add(icon));
    }

    const relativePath = path.relative(projectRoot, file);

    resolvedBy.forEach((count, component) => {
      resolvedByComponent.set(
        component,
        (resolvedByComponent.get(component) || 0) + count
      );
    });

    unresolved.forEach((usage) => {
      allUnresolved.push({ ...usage, file: relativePath });
    });

    forwarded.forEach((usage) => {
      allForwarded.push({ ...usage, file: relativePath });
    });

    scraped.forEach((usage) => {
      allScraped.push({ ...usage, file: relativePath });
    });

    const icons = Array.from(iconNames);

    if (icons.length > 0) {
      filesWithIcons++;
      icons.forEach((icon) => allIcons.add(icon));

      console.log(`   📄 ${relativePath}: ${icons.length} icon(s)`);
      icons.forEach((icon) => console.log(`      - ${icon}`));
    }
  });

  // A `name={name}` pass-through is only resolved if the wrapper it belongs to was
  // matched somewhere with a static name. Otherwise the icons behind it are unknown.
  allForwarded.forEach((usage) => {
    if (!resolvedByComponent.get(usage.wrapper)) {
      allUnresolved.push(usage);
    }
  });

  allUnresolved.sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);

  // Tailwind-style tier: validated icon literals anywhere in the scanned files,
  // attributed to the file that introduced them. Runs after the component pass so
  // only genuinely new names are credited to the literal scan.
  const viaLiteralScan = new Map();
  const dynamicConstructions = [];

  if (smart) {
    sources.forEach(({ file, content }) => {
      const { icons, constructions } = literalScanFile(content, userConfig.extraPrefixes);
      const relativePath = path.relative(projectRoot, file);

      icons.forEach((icon) => {
        if (!allIcons.has(icon) && !viaLiteralScan.has(icon)) {
          viaLiteralScan.set(icon, relativePath);
        }
      });

      constructions.forEach((construction) => {
        dynamicConstructions.push({ ...construction, file: relativePath });
      });
    });

    viaLiteralScan.forEach((_file, icon) => allIcons.add(icon));
  }

  if (userConfig.exclude.length > 0) {
    Array.from(allIcons).forEach((icon) => {
      if (userConfig.exclude.some((pattern) => matchesIconGlob(pattern, icon))) {
        allIcons.delete(icon);
        viaLiteralScan.delete(icon);
      }
    });
  }

  const byPrefix = {};
  Array.from(allIcons).forEach((icon) => {
    const [prefix] = icon.split(":");
    if (!byPrefix[prefix]) {
      byPrefix[prefix] = [];
    }
    byPrefix[prefix].push(icon);
  });

  console.log(`\n   📊 Summary:`);
  console.log(`   - Files scanned: ${sources.length}`);
  console.log(`   - Files with IconifyIcon import: ${filesWithImport}`);
  console.log(`   - Files with icons: ${filesWithIcons}`);
  console.log(`   - Total unique icons: ${allIcons.size}\n`);

  if (wrappers.names.size > 0) {
    console.log(
      `   Wrapper components traced: ${Array.from(wrappers.names).sort().join(", ")}\n`
    );
  }

  if (allIcons.size > 0) {
    console.log("   Icons by prefix:");
    Object.keys(byPrefix)
      .sort()
      .forEach((prefix) => {
        console.log(`   - ${prefix}: ${byPrefix[prefix].length} icons`);
      });
    console.log("");
  }

  if (allScraped.length > 0) {
    console.log(
      `   📎 ${allScraped.length} dynamic expression(s) resolved from their string literals:`
    );
    allScraped.forEach((usage) => {
      console.log(
        `   - ${usage.file}:${usage.line} <${usage.component} name=${usage.expression} /> → ${usage.icons.join(", ")}`
      );
    });
    console.log("");
  }

  if (viaLiteralScan.size > 0) {
    console.log(
      `   🔎 ${viaLiteralScan.size} icon(s) found by literal scan (validated against ${
        KNOWN_PREFIXES.size + userConfig.extraPrefixes.size
      } known prefixes):`
    );
    Array.from(viaLiteralScan.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .forEach(([icon, file]) => {
        console.log(`   - ${icon} (${file})`);
      });
    console.log("");
  }

  if (dynamicConstructions.length > 0) {
    console.log(
      `⚠️  [Iconify] ${dynamicConstructions.length} dynamically constructed icon name(s) cannot be resolved:`
    );
    dynamicConstructions.forEach((construction) => {
      console.log(
        `   - ${construction.file}:${construction.line} \`${construction.head}\${...}\``
      );
    });
    console.log("");
    console.log("   Use complete icon names where possible, or bundle by pattern");
    console.log("   in package.json:");
    console.log(
      `     { "iconify": { "icons": ["${dynamicConstructions[0].suggestion}"] } }\n`
    );
  }

  if (allUnresolved.length > 0) {
    console.log(
      `⚠️  [Iconify] ${allUnresolved.length} icon usage(s) could not be resolved statically:`
    );
    allUnresolved.slice(0, CONFIG.maxUnresolvedReported).forEach((usage) => {
      console.log(
        `   - ${usage.file}:${usage.line} <${usage.component} name=${usage.expression} />`
      );
    });

    if (allUnresolved.length > CONFIG.maxUnresolvedReported) {
      console.log(
        `   ... and ${allUnresolved.length - CONFIG.maxUnresolvedReported} more`
      );
    }

    console.log("");
    console.log("   These icons are fetched from the Iconify API at runtime instead of");
    console.log("   being bundled. To bundle them, list them in package.json:");
    console.log('     { "iconify": { "icons": ["mdi:heart", "mdi:home"] } }\n');
  }

  return {
    icons: Array.from(allIcons).sort(),
    byPrefix,
    unresolved: allUnresolved,
    scraped: allScraped,
    viaLiteralScan: Array.from(viaLiteralScan.entries())
      .map(([icon, file]) => ({ icon, file }))
      .sort((a, b) => a.icon.localeCompare(b.icon)),
    dynamicConstructions,
    iconGlobs: userConfig.iconGlobs,
    wrapperComponents: Array.from(wrappers.names).sort(),
    stats: {
      filesScanned: sources.length,
      filesWithImport,
      filesWithIcons,
      totalIcons: allIcons.size,
      unresolvedUsages: allUnresolved.length,
      literalScanIcons: viaLiteralScan.size,
    },
  };
}

module.exports = {
  scanProject,
  extractIconNames,
  extractIconNamesFromComponent,
  hasIconifyImport,
  extractStringLiterals,
  matchesIconGlob,
};

if (require.main === module) {
  const result = scanProject();

  if (result.icons.length === 0) {
    console.log("⚠️  No IconifyIcon components found in codebase\n");
    console.log("   Make sure you:");
    console.log(
      '   1. Import IconifyIcon from "@huymobile/react-native-iconify"'
    );
    console.log('   2. Use <IconifyIcon name="prefix:icon-name" /> in JSX\n');
    console.log("   Example:");
    console.log(
      '     import { IconifyIcon } from "@huymobile/react-native-iconify";'
    );
    console.log('     <IconifyIcon name="mdi:home" size={24} />\n');
  } else {
    console.log("✅ Scan complete!\n");
  }

  process.exit(0);
}
